# Using python for running the tests, using the `cram` test framework.
language: python

# Python version to run tests with.
python:
  - "2.7"

env:
  - CRAM_SHELL=sh
  - CRAM_SHELL=bash
  - CRAM_SHELL=zsh

install:
  - "pip install -r requirements.txt --use-mirrors"

before_script:
  - "sudo apt-get install zsh"

script: "cram -v --shell=$CRAM_SHELL tests"
